name: Github to Bitbucket sync
# This action will sync the github repo with a backup bitbucket repo.
# This will allow LinuxGSM to use Bitbucket as and alternative download if github fails.
on:
  push:
    branches:
      - master
      - 'develop'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.BITBUCKET_SECRET }}

    - name: repo-sync
      uses: wei/git-sync@v2.1.0
      with:
        ssh_private_key: ${{ secrets.BITBUCKET_SECRET }}
        source_repo: "https://github.com/GameServerManagers/LinuxGSM"
        source_branch: "refs/heads/*"
        destination_repo: "git@bitbucket.org:GameServerManagers/linuxgsm.git"
        destination_branch: "refs/heads/*"
