name: Backup Repo
# This action will sync the github repo with a backup bitbucket repo.
# This will allow LinuxGSM to use Bitbucket as and alternative download if github fails.
on:
  push:
    branches:    
      - master
      - 'develop'
      - 'feature/update-lgsm'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.BITBUCKET_SECRET }}
        ssh_private_key: ${{ secrets.BITBUCKET_SECRET }}

    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/GameServerManagers/LinuxGSM"
        source_branch: "refs/heads/*"
        destination_repo: "git@bitbucket.org:GameServerManagers/linuxgsm.git"
        destination_branch: "refs/heads/*"
        ssh_private_key: ${{ secrets.BITBUCKET_SECRET }}
